upcoming: [DI-19384] - Adding notification channels components to Create Alert From
ACLPManager/manager pull request #114
Opened 2024-12-30 18:53 UTC by santoshp210-akamai

## Description 📝

Highlight the Pull Request's context and intentions.

## Changes  🔄

List any change(s) relevant to the reviewer.

- ...
- ...

## Target release date 🗓️

Please specify a release date (and environment, if applicable) to guarantee timely review of this PR. If exact date is not known, please approximate and update it as needed.

## Preview 📷

**Include a screenshot or screen recording of the change.**

:lock: Use the [Mask Sensitive Data](https://cloud.linode.com/profile/settings) setting for security.

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 📷 | 📷 |

## How to test 🧪

### Prerequisites

(How to setup test environment)

- ...
- ...

### Reproduction steps

(How to reproduce the issue, if applicable)

- [ ] ...
- [ ] ...

### Verification steps

(How to verify changes)

- [ ] ...
- [ ] ...

<details>
<summary> Author Checklists </summary>

## As an Author, to speed up the review process, I considered 🤔

*Check all that apply*

- [ ] Use React components instead of HTML Tags
- [ ] Proper naming conventions like cameCase for variables & Function & snake_case for constants
- [ ] Use appropriate types & avoid using "any"
- [ ] No type casting & non-null assertions
- [ ] Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] Providing/Improving test coverage
- [ ] Use sx props to pass styles instead of style prop
- [ ] Add JSDoc comments for interface properties & functions
- [ ] Use strict equality (===) instead of double equal (==)
- [ ] Use of named arguments (interfaces) if function argument list exceeds size 2
- [ ] Destructure the props
- [ ] Keep component size small & move big computing functions to separate utility
- [ ] 📱 Providing mobile support

<br/>

- [ ] I have read and considered all applicable items listed above.

## As an Author, before moving this PR from Draft to Open, I confirmed ✅

- [ ] All unit tests are passing
- [ ] TypeScript compilation succeeded without errors
- [ ] Code passes all linting rules

</details>

---

## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**

- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `change`: Modifying an existing visual UI instance. Such as a component or a feature.
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `upcoming`: A new feature that is in progress, not visible to users yet, and usually behind a feature flag.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

---

2025-01-07 04:12 UTC, venkymano-akamai commented on packages/api-v4/src/cloudpulse/alerts.ts
> +    );
Is there an ESLint formatting issue here

2025-01-07 04:14 UTC, venkymano-akamai commented on packages/api-v4/src/cloudpulse/types.ts
> +  alerts: {
instead of hardcoding the json here, can we create a nice type here for alerts like

**NotificationChannelAlerts**

2025-01-07 04:14 UTC, venkymano-akamai commented on packages/api-v4/src/cloudpulse/types.ts
> +    email: {
Here also, we can create simple types like, AlertNotificationEmail, AlertNotificationSlack etc., and link it

2025-01-07 04:17 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
> +  const onChangeNotifications = (notifications: NotificationChannel[]) => {
I think we should surround these methods with useCallback to avoid unnecessary creations

2025-01-07 04:17 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
> +  const onSubmitAddNotification = (notificationId: number) => {
same here

2025-01-07 04:18 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
> +    // return (
remove unwanted comments

2025-01-07 04:19 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
> +            onClickAddNotification={() => setOpenAddNotification(true)}
Lets also move this piece to a function and also have a nice callback

2025-01-07 04:19 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
> +              onClose={() => setOpenAddNotification(false)}
Create a function for this and reuse in above place and here, and also use useCallback

2025-01-07 04:20 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
> +                onCancel={() => setOpenAddNotification(false)}
same here

2025-01-07 04:20 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/Metric.tsx
> +          theme.name === 'light'
This needs to be changed, please use getAlertBoxStyles function from utils.ts

2025-01-07 04:22 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddChannelListing.test.tsx
> +    await user.click(clearButton);
we can just use userEvent.click

2025-01-07 04:22 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddChannelListing.test.tsx
> +  const user = userEvent.setup();
I think no need for this, everywhere we can just use userEvent.click, userEvent.clear like that

2025-01-07 04:23 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddChannelListing.test.tsx
> +    const container = renderWithThemeAndHookFormContext({
here, you can destructure the {getByText} method and use it

2025-01-07 04:23 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddChannelListing.test.tsx
> +    const container = renderWithThemeAndHookFormContext({
same here, destructure whatever methods you want and use

2025-01-07 04:24 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddChannelListing.test.tsx
> +  {
Here, we should use factory, create a notification channel factory and use it

2025-01-07 04:25 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddChannelListing.tsx
> +   * notification channel list passed to the component to be displayed in the form
Can we please start the comments with capital letters, correct in all over this PR

2025-01-07 04:25 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddChannelListing.tsx
> +                sx={(theme) => ({
use getAlertBoxStyles from utils.ts and append additional styles you require

2025-01-07 04:26 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddChannelListing.tsx
> +                    paddingBottom: 1,
we can start using theme.spacing(1), theme.spacing(2) here

2025-01-07 04:27 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddChannelListing.tsx
> +                    width: '100%',
does percentage makes sense here, we can use appropriate PX values to the style here also.

2025-01-07 04:27 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddChannelListing.tsx
> +                        ChannelTypeOptions.find(
Here it is in pascal case, what is the convention we need to follow, i thought we are using camel case for constants

2025-01-07 04:29 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddChannelListing.tsx
> +      <Box mt={1}>
why do we need a box here, isn't button just enough

2025-01-07 04:30 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.test.tsx
> +const mockData: NotificationChannel[] = [
same, we need to create a factory and use it

2025-01-07 04:31 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.test.tsx
> +    const container = renderWithTheme(
same, for UT's in this PR, lets destructure the required methods and use it

2025-01-07 04:35 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.tsx
> +                theme.name === 'light'
better not to use this conditional check...

2025-01-07 04:36 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.tsx
> +          {/* This is not the complete end solution, this is to satsify the current requirements of email type channels and the default email notification channel */}
we don't need to add this comment, we should maintain somewhere in our backlog

2025-01-07 04:37 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/constants.ts
> +export const ChannelTypeOptions: Item<string, ChannelTypes>[] = [
same, why we need to maintain a list starting here, we can maintain and map and engineer that to list

2025-01-07 04:39 UTC, venkymano-akamai commented on packages/manager/src/mocks/serverHandlers.ts
> +    const response = {
factory needed for sure

2025-01-07 04:40 UTC, venkymano-akamai requested changes
Please go through the comments, 
@santoshp210-akamai , I have reviewed it but definitely we need split this PR into two

FYI -  @kmuddapo

2025-01-07 04:49 UTC, kmuddapo commented
> Please go through the comments, @santoshp210-akamai , I have reviewed it but definitely we need split this PR into two
> 
> FYI - @kmuddapo
> 
> Also please resolve the conflicts

Yes!!, Lets split this to 2 parts, *00+ lines is not a good deal

2025-01-07 07:34 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddChannelListing.tsx
> +export const AddChannelListing = (props: ChannelListProps) => {
@santoshp210-akamai , Lets have all the components surrounded by React.memo, to avoid unnecessary re-renders, when you start using useCallbacks for you onChangeNotifications, onClickAddNotification, it will optimize its rendering

Can we use that here

2025-01-07 08:06 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddChannelListing.test.tsx
> +    await user.click(clearButton);
I was using it as it was mentioned in the docs https://testing-library.com/docs/user-event/intro/#writing-tests-with-userevent. Is it required to change it back and use `userEvent` everywhere

2025-01-07 08:14 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddChannelListing.tsx
> +      <Box mt={1}>
There are some styling changes required if we were to remove the Box component. I will add margin and check if it works for all screen sizes.

2025-01-07 08:21 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.tsx
> +                theme.name === 'light'
We have used similar styling for MetricThreshold component and it was approved and merged , is the change still required ?

2025-01-07 08:22 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/constants.ts
> +export const ChannelTypeOptions: Item<string, ChannelTypes>[] = [
As discussed before we can have this change for now and then make the changes in a single separate PR, right ?

2025-01-08 05:19 UTC, venkymano-akamai commented
@nikhagra-akamai / @ankita-akamai - may be we can do parallel reviews on this one. To get it merged.

This will help in merging notification channel for alert details

2025-01-08 05:29 UTC, ankita-akamai commented
@santoshp210-akamai  would you be able to give some pr description and screenshots to see what exactly is changed. As this pr is code heavy, need that to review!

2025-01-08 08:23 UTC, ankita-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.tsx
> +          (template) => template.channel_type === channelTypeWatcher
type check here for template?

2025-01-08 08:32 UTC, ankita-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.tsx
> +  const selectedTypeTemplate =
This `selectedTypeTemplate` is a little confusing.

2025-01-08 09:01 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.tsx
> +  const selectedTypeTemplate =
Any suggestions

2025-01-08 09:27 UTC, ankita-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddChannelListing.tsx
> +                    theme.name === 'light'
here also, need to get rid of the conditional check.. refer https://github.com/linode/manager/pull/11466

2025-01-08 13:52 UTC, nikhagra-akamai requested changes

2025-01-08 13:52 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
> +  const { data: notificationData } = useNotificationChannels();
please handle error & loading state

2025-01-08 13:52 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
> +  const onChangeNotifications = (notifications: NotificationChannel[]) => {
It'll not be required because the component using it will anyway going to re-render on every re-rendering of parent, so lets avoid over using of hook

2025-01-08 13:52 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.tsx
> +import { Autocomplete } from '@linode/ui';
optimize this import statement as per eslint 

```suggestion
import { Box, Typography, Autocomplete } from '@linode/ui';
```

2025-01-08 13:52 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.tsx
> +  }, [selectedTypeTemplate]);
can we avoid using memo if it is not heavy computation?

2025-01-08 13:52 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/RenderChannelDetails.tsx
> +      template.channel_type === 'email' &&
why dual condition check? We have already put the check inside `if`

2025-01-08 13:57 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/RenderChannelDetails.tsx
> +      template.channel_type === 'email' &&
The second condition implicitly casts the NotificationChannel into NotificationChannelEmail which has different `content` json object , so to use `template.email.content` I'm doing the condition check again.

2025-01-08 13:58 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.tsx
> +  }, [selectedTypeTemplate]);
This is so that it won't re calculate the templateOptions for ever time. Will check again for the re-computation and remove if it's not needed.

2025-01-08 14:00 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/RenderChannelDetails.tsx
> +      template.channel_type === 'email' &&
extra condition is not required you remove that 

```suggestion
if (template.channel_type === 'email') {
    return template.content.email.email_addresses.map(
      (email: string, id: number) => <Chip key={id} label={email} />
    );
  }
```

2025-01-08 14:03 UTC, nikhagra-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.tsx
> +  }, [selectedTypeTemplate]);
yes check and if it is not frequent re-computation then we can avoid memo

2025-01-08 14:03 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.tsx
> +          (template) => template.channel_type === channelTypeWatcher
Implicitly `template` is going to be `NotificationChannel `type only and since we are sure that `templateData` is `NotificationChannel[]` , do we need another check.

2025-01-08 15:33 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddChannelListing.test.tsx
> +    await user.click(clearButton);
You can use it, but just following the other UT files in the code, we can just use userEvent

2025-01-08 15:34 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.tsx
> +import { Autocomplete } from '@linode/ui';
@santoshp210-akamai , we should enable and use ESLint as formatter in plugin setting for these

2025-01-08 15:35 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.tsx
> +  const selectedTypeTemplate =
@santoshp210-akamai , here you can use selectedChannelTypeTemplate

2025-01-08 15:35 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.tsx
> +          (template) => template.channel_type === channelTypeWatcher
if the templates type is inferred , don't need to add

2025-01-08 15:37 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/constants.ts
> +export const ChannelTypeOptions: Item<string, ChannelTypes>[] = [
No, this is brand new PR you are going to create for linode/develop, may be instead of this create a map and convert that to options

2025-01-08 15:38 UTC, venkymano-akamai commented on packages/manager/src/queries/cloudpulse/alerts.ts
> +};
There seems to some eslint issue here as well

2025-01-08 15:44 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.tsx
> +import { Autocomplete } from '@linode/ui';
I have the ESLint formatter plugin, but for this it doesn't show any warning

2025-01-08 15:52 UTC, venkymano-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.tsx
> +  }, [selectedTypeTemplate]);
@santoshp210-akamai ,  we can get rid of this templateOptions all together, just use this and autocomplete takes care of it

```
<Box>
            <Controller
              render={({ field, fieldState }) => (
                <Autocomplete
                  onChange={(_, selected: NotificationChannel, reason) => {
                    field.onChange(
                      reason === 'selectOption' ? selected.label : null
                    );
                  }}
                  value={
                    selectedTypeTemplate?.find(
                      (option) => option.label === field.value
                    ) ?? null
                  }
                  data-testid="channel-label"
                  disabled={!selectedTypeTemplate}
                  errorText={fieldState.error?.message}
                  key={channelTypeWatcher}
                  label="Channel"
                  onBlur={field.onBlur}
                  options={selectedTypeTemplate ?? []}
                  placeholder="Select a Channel"
                />
              )}
              control={control}
              name="label"
            />
          </Box>
```

2025-01-09 21:13 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/NotificationChannel/AddNotificationChannel.tsx
> +  }, [selectedTypeTemplate]);
Planning to keep the TypeOptions as the data is not in the form {label, value}

2025-01-10 10:33 UTC, ankita-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/TriggerConditions.test.tsx
linting fix: There is an odd newline row 16, can you remove and put some space before describe?

2025-01-10 10:36 UTC, santoshp210-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/Criteria/TriggerConditions.test.tsx
Technically this component has already been merged to the linode/develop. I edited variable names for consistency so this file also got reflected. The current components are AddChannelListing, AddNotificationChannel, RenderChannelDetails that are part of the feature. But I will make that change.

2025-01-10 10:48 UTC, ankita-akamai commented on packages/manager/src/features/CloudPulse/Alerts/CreateAlert/CreateAlertDefinition.tsx
> +
We don't require useCallback here as well, referring to Nikhil's comment above.

2025-01-10 10:52 UTC, ankita-akamai commented
@santoshp210-akamai approving pending 1/2 comments..

2025-01-10 10:53 UTC, ankita-akamai approved these changes

2025-01-10 11:04 UTC, nikhagra-akamai approved these changes

2025-01-10 11:05 UTC, merged