Error handling
ACLPManager/manager pull request #56
Opened 2024-10-29 10:02 UTC by agorthi-akamai

## Description 📝
Highlight the Pull Request's context and intentions.

## Changes  🔄
List any change relevant to the reviewer.
- ...
- ...

## Target release date 🗓️
Please specify a release date to guarantee timely review of this PR. If exact date is not known, please approximate and update it as needed.

## Preview 📷
**Include a screenshot or screen recording of the change**

:bulb: Use `<video src="" />` tag when including recordings in table.

| Before  | After   |
| ------- | ------- |
| 📷 | 📷 |

## How to test 🧪

### Prerequisites
(How to setup test environment)
- ...
- ...

### Reproduction steps
(How to reproduce the issue, if applicable)
- ...
- ...

### Verification steps
(How to verify changes)
- ...
- ...

## As an Author I have considered 🤔

*Check all that apply*

- [ ] Use React components instead of HTML Tags
- [ ] Proper naming conventions like cameCase for variables & Function & snake_case for constants
- [ ] Use appropriate types & avoid using "any"
- [ ] No type casting & non-null assertions
- [ ] Adding a [changeset](https://github.com/linode/manager/blob/develop/docs/CONTRIBUTING.md#writing-a-changeset)
- [ ] Providing/Improving test coverage
- [ ] Use sx props to pass styles instead of style prop
- [ ] Add JSDoc comments for interface properties & functions
- [ ] Use strict equality (===) instead of double equal (==)
- [ ] Use of named arguments (interfaces) if function argument list exceeds size 2
- [ ] Destructure the props
- [ ] Keep component size small & move big computing functions to separate utility
- [ ] 📱 Providing mobile support

---
## Commit message and pull request title format standards

> **Note**: Remove this section before opening the pull request
**Make sure your PR title and commit message on squash and merge are as shown below**

`<commit type>: [JIRA-ticket-number] - <description>`

**Commit Types:**
- `feat`: New feature for the user (not a part of the code, or ci, ...).
- `fix`: Bugfix for the user (not a fix to build something, ...).
- `change`: Modifying an existing visual UI instance. Such as a component or a feature.
- `refactor`: Restructuring existing code without changing its external behavior or visual UI. Typically to improve readability, maintainability, and performance.
- `test`: New tests or changes to existing tests. Does not change the production code.
- `upcoming`: A new feature that is in progress, not visible to users yet, and usually behind a feature flag.

**Example:** `feat: [M3-1234] - Allow user to view their login history`

---

2024-10-29 13:38 UTC, nikhagra-akamai approved these changes

2024-11-04 02:26 UTC, venkymano-akamai commented on packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-validation.spec.ts
> +        statusCode: 400,
@agorthi-akamai , eventhough 400 is good that it is thrown by API, we can have 500 as default for now, as it indicates there is some real failure in API rather UI sending a bad request

2024-11-04 02:28 UTC, venkymano-akamai commented on packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-validation.spec.ts
> +  it('should return error response when fetching token api request', () => {
In some places api is in small and in some places api is like API, lets be consistent and use API

2024-11-04 02:31 UTC, venkymano-akamai commented on packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-validation.spec.ts
>      mockGetLinodes([mockLinode]);
why this mock is needed?

2024-11-04 02:36 UTC, venkymano-akamai commented on packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-validation.spec.ts
> +    cy.intercept(
FYI, as per our discussions, I believe in other places also, the intercept is handled within the test cases, rather putting in a intercepts.ts file.

cc- @kmuddapo , @nikhagra-akamai

2024-11-04 02:37 UTC, venkymano-akamai commented on packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-validation.spec.ts
> +    }).as('fetchCluster');
don't use alias until you are dependant on it. This is one of the comments we received in our previous PR.

2024-11-04 02:38 UTC, venkymano-akamai commented on packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-validation.spec.ts
> +    }).as('fetchCluster');
```suggestion
    });
```

2024-11-04 02:38 UTC, venkymano-akamai commented on packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-validation.spec.ts
> +    }).as('fetchDashboardById');
same everywhere don't use alias until it is required

2024-11-04 02:40 UTC, venkymano-akamai commented on packages/manager/cypress/e2e/core/cloudpulse/cloudpulse-validation.spec.ts
> +    cy.findByText(clusterName).should('be.visible');
why we need this validations here, it is not needed as it is covered in a separate test file

2024-11-04 02:43 UTC, venkymano-akamai requested changes
I have left review comment, please check and update

2024-11-04 05:12 UTC, agorthi-akamai commented
I've addressed every comment; kindly have a look.

2024-11-04 05:33 UTC, venkymano-akamai commented
@agorthi-akamai , **describe('DbasS API Error Handling', () => {**, please reply to the comment regarding this or fix it

2024-11-04 05:50 UTC, venkymano-akamai approved these changes

2024-11-04 05:50 UTC, merged